# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
  branches:
    include:
    - "*"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Go@0
      displayName: Run Golang Tests
      inputs:
        command: test
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: 'gql-server'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'Docker'
        repository: 'gql-server'
        command: 'push'
        tags: '$(tag)'
