trigger:
  - master

pr:
  branches:
    include:
      - "*"

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  repository: "gql-server"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Go@0
            displayName: Run Golang Tests
            inputs:
              command: test

  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: "$(repository)"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "$(tag)"

          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: "Docker"
              repository: "gql-server"
              command: "push"
              tags: "$(tag)"

      - job: Publish
        displayName: "Publish Terraform"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "terraform"
              ArtifactName: "terraform"
