// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelgen

type CreateAddressInput struct {
	Name       string  `json:"name"`
	Street1    string  `json:"street1"`
	Street2    *string `json:"street2"`
	City       string  `json:"city"`
	State      *string `json:"state"`
	PostalCode int     `json:"postalCode"`
	Country    string  `json:"country"`
}

type CreateClientInput struct {
	Name            string              `json:"name"`
	Website         *string             `json:"website"`
	VatNumber       *string             `json:"vatNumber"`
	BusinessNumber  *string             `json:"businessNumber"`
	Phone           *string             `json:"phone"`
	BillingAddress  *CreateAddressInput `json:"billingAddress"`
	ShippingAddress *CreateAddressInput `json:"shippingAddress"`
}

type CreateCompanyInput struct {
	Name    string   `json:"name"`
	Code    string   `json:"code"`
	Domains []string `json:"domains"`
}

type UpdateAddressInput struct {
	Name       *string `json:"name"`
	Street1    *string `json:"street1"`
	Street2    *string `json:"street2"`
	City       *string `json:"city"`
	State      *string `json:"state"`
	PostalCode *int    `json:"postalCode"`
	Country    *string `json:"country"`
}

type UpdateClientInput struct {
	Name            *string             `json:"name"`
	Website         *string             `json:"website"`
	VatNumber       *string             `json:"vatNumber"`
	BusinessNumber  *string             `json:"businessNumber"`
	Phone           *string             `json:"phone"`
	BillingAddress  *CreateAddressInput `json:"billingAddress"`
	ShippingAddress *CreateAddressInput `json:"shippingAddress"`
}
